"""Initial migration

Revision ID: 3f8bd1fb21d3
Revises: 
Create Date: 2023-08-12 16:08:33.055642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8bd1fb21d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar_file', sa.String(length=20), nullable=False),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('transcription', sa.String(length=200), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phrases_body'), ['body'], unique=False)
        batch_op.create_index(batch_op.f('ix_phrases_translation'), ['translation'], unique=False)

    op.create_table('wordlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wordlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wordlists_title'), ['title'], unique=True)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_timestamp'), ['timestamp'], unique=False)

    op.create_table('phrase_example_registrations',
    sa.Column('phrase_id', sa.Integer(), nullable=True),
    sa.Column('example_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['example_id'], ['examples.id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], )
    )
    op.create_table('phrase_wordlist_registrations',
    sa.Column('phrase_id', sa.Integer(), nullable=True),
    sa.Column('wordlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.ForeignKeyConstraint(['wordlist_id'], ['wordlists.id'], )
    )
    op.create_table('wordlist_subscriptions',
    sa.Column('wordlist_id', sa.Integer(), nullable=True),
    sa.Column('user_is', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_is'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wordlist_id'], ['wordlists.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordlist_subscriptions')
    op.drop_table('phrase_wordlist_registrations')
    op.drop_table('phrase_example_registrations')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_timestamp'))

    op.drop_table('comments')
    with op.batch_alter_table('wordlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordlists_title'))

    op.drop_table('wordlists')
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phrases_translation'))
        batch_op.drop_index(batch_op.f('ix_phrases_body'))

    op.drop_table('phrases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('examples')
    # ### end Alembic commands ###
