version: '3'
services:
  fancywords:
    build: .
    volumes:
      - ./static/:/home/FancyWords/app/static/
    ports:
      - "8003:5000"
    env_file: .env
    links:
      - postgres:postgres
    restart: always
  postgres:
    image: postgres:14.3
    env_file: .env-postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
